import swaggerJsdoc from 'swagger-jsdoc';

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'PhiloMedia REST API',
      version: '2.0.0',
      description:
        'A RESTful API for managing PhiloMedia philosophical quotes, curated matches between media and philosophy, and AI-powered quote generation.',
      contact: {
        name: 'PhiloMedia Support',
        url: 'https://philomedia.onrender.com',
      },
    },
    servers: [
      {
        url: 'https://philomedia.onrender.com',
        description: 'Production Server',
      },
      {
        url: 'http://localhost:3000',
        description: 'Development Server',
      },
    ],
    components: {
      securitySchemes: {
        CookieAuth: {
          type: 'apiKey',
          in: 'cookie',
          name: 'connect.sid',
        },
      },
      schemas: {
        // ─── Quote ────────────────────────────────────────────────────────────
        Quote: {
          type: 'object',
          required: ['quoteText', 'authorName'],
          properties: {
            quoteText: {
              type: 'string',
              description: 'The philosophical quote text.',
              example: 'The unexamined life is not worth living.',
            },
            authorName: {
              type: 'string',
              description: 'The author or philosopher of the quote.',
              example: 'Socrates',
            },
            themes: {
              type: 'array',
              items: { type: 'string' },
              description: 'Philosophical themes associated with the quote.',
              example: ['self-knowledge', 'virtue'],
            },
            isGenerated: {
              type: 'boolean',
              description: 'Whether this quote was generated by AI.',
              example: false,
            },
            generationContext: {
              type: 'object',
              description: 'Metadata about the AI generation (only present when isGenerated is true).',
              properties: {
                mode: { type: 'string', enum: ['by-theme', 'by-philosopher'] },
                inputThemes: { type: 'array', items: { type: 'string' } },
                inputPhilosopher: { type: 'string' },
                model: { type: 'string' },
                generatedAt: { type: 'string', format: 'date-time' },
              },
            },
          },
        },

        // ─── Match ────────────────────────────────────────────────────────────
        Match: {
          type: 'object',
          required: ['tmdbId', 'quoteId', 'mediaType'],
          properties: {
            tmdbId: {
              type: 'string',
              description: 'The unique ID of the media on TMDB.',
              example: '157336',
            },
            quoteId: {
              type: 'string',
              description: 'The ID of the quote matched to the media.',
              example: '66a1b0267f5e8254c25d81f2',
            },
            mediaType: {
              type: 'string',
              enum: ['movie', 'tv', 'anime', 'unknown'],
              description: 'The type of media.',
              example: 'movie',
            },
          },
        },

        // ─── AI Quote Requests ────────────────────────────────────────────────
        GenerateByThemeRequest: {
          type: 'object',
          required: ['themes'],
          properties: {
            themes: {
              type: 'array',
              items: { type: 'string' },
              minItems: 1,
              maxItems: 5,
              description: 'List of philosophical themes (use GET /api/ai/quotes/themes for valid values).',
              example: ['existentialism', 'freedom'],
            },
            save: {
              type: 'boolean',
              description: 'If true, saves the generated quote to the database.',
              example: false,
            },
          },
        },

        GenerateByPhilosopherRequest: {
          type: 'object',
          required: ['philosopher'],
          properties: {
            philosopher: {
              type: 'string',
              description: 'Name of the philosopher whose style to emulate.',
              example: 'Nietzsche',
            },
            theme: {
              type: 'string',
              description: 'Optional theme to guide the generation.',
              example: 'power',
            },
            save: {
              type: 'boolean',
              description: 'If true, saves the generated quote to the database.',
              example: false,
            },
          },
        },

        // ─── AI Quote Response ────────────────────────────────────────────────
        AIQuoteResponse: {
          type: 'object',
          properties: {
            quote: {
              type: 'object',
              properties: {
                quoteText: { type: 'string', example: 'To will is to create reality.' },
                authorName: { type: 'string', example: 'Friedrich Nietzsche' },
                themes: { type: 'array', items: { type: 'string' }, example: ['existentialism', 'power'] },
                isGenerated: { type: 'boolean', example: true },
                generationContext: {
                  type: 'object',
                  properties: {
                    mode: { type: 'string', example: 'by-philosopher' },
                    inputPhilosopher: { type: 'string', example: 'Nietzsche' },
                    model: { type: 'string', example: 'gemini-2.0-flash' },
                    generatedAt: { type: 'string', format: 'date-time' },
                  },
                },
              },
            },
            explanation: {
              type: 'string',
              example: 'This quote reflects Nietzsche\'s view of the will to power as the fundamental creative force.',
            },
            saved: {
              type: 'boolean',
              example: false,
            },
          },
        },
      },
    },
    tags: [
      {
        name: 'Quotes',
        description: 'Endpoints to manage philosophical quotes',
      },
      {
        name: 'Matches',
        description: 'Endpoints to manage associations between media and quotes',
      },
      {
        name: 'AI Quotes',
        description: 'AI-powered philosophical quote generation using Google Gemini',
      },
    ],
  },
  apis: ['./src/routes/*.js'],
};

export const specs = swaggerJsdoc(options);