/**
 * Canonical TMDB candidate ranking + quote profile (shared with browser bundle).
 * The browser copy is generated by `npm run extract:media-rank` into
 * `public/scripts/mediaRankCore.js` (import paths rewritten to `./`).
 */
import { analyzeWorkForThemes } from '../../../public/scripts/hermeneutics.js';
import { THEME_DATABASE } from '../../../public/scripts/themedatabase.js';
import { flattenThemeGenreHint } from '../../../public/scripts/domain/themeGenreHints.js';
import {
  getCuratedPhilosophicalProfile,
  scorePhilosophicalTagsAgainstThemeWeights,
} from '../../../public/scripts/curatedPhilosophicalProfiles.js';
import { curatedQuoteMatches } from '../../../public/scripts/curatedmatches.js';

const HOME_RESULT_LIMIT = 10;

const KEYWORD_STOPWORDS = new Set([
  'about', 'after', 'alone', 'among', 'around', 'being', 'between', 'beyond',
  'choice', 'choices', 'emotion', 'feelings', 'freedom', 'future', 'good',
  'great', 'human', 'humanity', 'ignorance', 'journey', 'knowledge', 'life',
  'lives', 'meaning', 'moral', 'morality', 'nature', 'other', 'people',
  'person', 'power', 'reason', 'reality', 'society', 'story', 'struggle',
  'their', 'there', 'these', 'those', 'through', 'truth', 'virtue', 'world',
  'wrong',
]);

const THEME_TEXT_SIGNAL_OVERRIDES = {
  hedonism: [
    'happiness', 'pleasure', 'pain', 'suffering', 'wellbeing', 'well being',
    'desire', 'satisfaction', 'comfort', 'health', 'patient', 'patients',
    'joy', 'misery', 'harm', 'benefit',
  ],
  utilitarianism: [
    'greater good', 'consequence', 'consequences', 'save lives', 'saving lives',
    'lives', 'sacrifice', 'survival', 'patient', 'patients', 'hospital',
    'doctor', 'surgeon', 'medicine', 'crime', 'police', 'detective',
    'criminal', 'criminals', 'justice', 'punishment', 'institution',
    'institutions', 'system', 'policy', 'social', 'drug', 'drugs',
    'murder', 'killer', 'corruption', 'community', 'public',
  ],
  virtue: ['virtue', 'honor', 'honour', 'courage', 'duty', 'character', 'integrity', 'sacrifice'],
  'political-philosophy': ['government', 'state', 'law', 'power', 'institution', 'system', 'policy', 'public'],
  'social-justice': ['justice', 'inequality', 'poverty', 'class', 'rights', 'community', 'system', 'institution'],
  'power-corruption': ['power', 'corruption', 'control', 'authority', 'crime', 'greed', 'ambition'],
  'truth-deception': ['truth', 'lie', 'lies', 'deception', 'secret', 'illusion', 'conspiracy'],
};

export function normalizeText(text) {
  if (!text) return '';

  return text
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .replace(/[\p{P}\p{S}]/gu, ' ')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim();
}

export function formatThemeLabel(theme) {
  return theme
    .split('-')
    .map(part => (part === 'ai' ? 'AI' : part.charAt(0).toUpperCase() + part.slice(1)))
    .join(' ');
}

function getThemeKeywords(theme, limit = 3) {
  return Object.entries(THEME_DATABASE[theme] || {})
    .filter(([keyword, weight]) => weight > 0 && keyword.length >= 5 && !KEYWORD_STOPWORDS.has(keyword))
    .sort((a, b) => b[1] - a[1] || b[0].length - a[0].length)
    .map(([keyword]) => keyword)
    .slice(0, limit);
}

function getBalancedPreferredGenres(rankedThemes, limit = 6) {
  const groups = rankedThemes
    .slice(0, 3)
    .map(theme => flattenThemeGenreHint(theme))
    .filter(group => group.length > 0);
  const genres = [];

  for (let index = 0; genres.length < limit && index < 4; index += 1) {
    groups.forEach(group => {
      const genre = group[index];
      if (genre && !genres.includes(genre) && genres.length < limit) {
        genres.push(genre);
      }
    });
  }

  return genres;
}

export function getThemeGenreFilters(rankedThemes) {
  return rankedThemes
    .slice(0, 3)
    .map(theme => {
      const genres = (flattenThemeGenreHint(theme) || []).slice(0, 2);
      return genres.length > 0
        ? { theme, withGenres: genres.join(',') }
        : null;
    })
    .filter(Boolean);
}

function createWeightMap(entries, explicitThemes = []) {
  const weights = new Map();

  explicitThemes.forEach((theme, index) => {
    if (!theme) return;
    weights.set(theme, (weights.get(theme) || 0) + Math.max(18, 36 - index * 5));
  });

  entries.forEach(({ theme, score }, index) => {
    weights.set(theme, (weights.get(theme) || 0) + score * 10 + Math.max(0, 12 - index));
  });

  const ranked = [...weights.entries()]
    .sort((a, b) => b[1] - a[1]);

  const total = ranked.reduce((sum, [, score]) => sum + score, 0) || 1;

  return new Map(
    ranked
      .slice(0, 6)
      .map(([theme, score]) => [theme, score / total])
  );
}

export function buildQuoteProfile(quoteData) {
  const explicitThemes = Array.isArray(quoteData.themes)
    ? quoteData.themes
        .map(theme => String(theme).trim().toLowerCase())
        .filter(theme => THEME_DATABASE[theme])
    : [];

  const inferredThemes = analyzeWorkForThemes(quoteData.quote || '');
  const themeWeights = createWeightMap(inferredThemes, explicitThemes);
  const rankedThemes = [...themeWeights.keys()];

  const keywords = [...new Set(
    rankedThemes
      .slice(0, 3)
      .flatMap(theme => getThemeKeywords(theme, 2))
  )].slice(0, 4);

  const preferredGenres = getBalancedPreferredGenres(rankedThemes);

  return {
    themes: rankedThemes,
    themeWeights,
    keywords,
    preferredGenres,
  };
}

function scoreThemeOverlap(themeWeights, candidateText) {
  if (!themeWeights.size) return 0;

  const candidateWeights = createWeightMap(analyzeWorkForThemes(candidateText));
  let score = 0;

  for (const [theme, sourceWeight] of themeWeights.entries()) {
    const candidateWeight = candidateWeights.get(theme);
    if (candidateWeight) {
      score += sourceWeight * candidateWeight * 140;
    }
  }

  return score;
}

function getThemeSignals(theme) {
  const databaseSignals = Object.entries(THEME_DATABASE[theme] || {})
    .filter(([, weight]) => weight > 0)
    .map(([keyword]) => keyword);
  const overrideSignals = THEME_TEXT_SIGNAL_OVERRIDES[theme] || [];

  return [...new Set([...databaseSignals, ...overrideSignals])];
}

function countSignalMatches(theme, candidateText) {
  const signals = getThemeSignals(theme);
  if (signals.length === 0) return 0;

  const normalized = normalizeText(candidateText);
  return signals.reduce((total, signal) => {
    const normalizedSignal = normalizeText(signal);
    if (!normalizedSignal) return total;
    return total + (normalized.includes(normalizedSignal) ? 1 : 0);
  }, 0);
}

function scoreThemeSignals(themeWeights, candidateText) {
  let score = 0;

  for (const [theme, sourceWeight] of themeWeights.entries()) {
    const matches = countSignalMatches(theme, candidateText);
    if (matches > 0) {
      score += Math.min(22, matches * 7) * sourceWeight;
    }
  }

  return score;
}

function hasThemeEvidence(theme, candidateWeights, candidateText) {
  if (candidateWeights.get(theme)) return true;
  return countSignalMatches(theme, candidateText) > 0;
}

function scorePrimaryThemeFit(profile, candidateWeights, candidateText) {
  const primaryThemes = profile.themes.slice(0, Math.min(2, profile.themes.length));
  if (primaryThemes.length === 0) {
    return { bonus: 0, penalty: 0, misses: [] };
  }

  const misses = primaryThemes.filter(theme => !hasThemeEvidence(theme, candidateWeights, candidateText));
  const matchedCount = primaryThemes.length - misses.length;

  return {
    bonus: matchedCount === primaryThemes.length ? 18 : matchedCount * 4,
    penalty: misses.reduce((total, theme, index) => total + (index === 0 ? 24 : 16), 0),
    misses,
  };
}

function scoreConceptDriftPenalty(profile, candidateWeights, candidateText) {
  const themes = new Set(profile.themes.slice(0, 2));
  let penalty = 0;

  if (themes.has('hedonism') && themes.has('utilitarianism')) {
    const hasUtilitarianEvidence = hasThemeEvidence('utilitarianism', candidateWeights, candidateText);
    const hasWellbeingEvidence = hasThemeEvidence('hedonism', candidateWeights, candidateText)
      || /\b(happiness|suffering|pain|harm|benefit|wellbeing|well being|patient|patients|health)\b/i.test(candidateText);
    const isPleasureOnly = /\b(erotic|sexual|desire|affair|seduction|lust)\b/i.test(candidateText)
      && !hasUtilitarianEvidence;

    if (!hasUtilitarianEvidence) penalty += 42;
    if (!hasWellbeingEvidence) penalty += 18;
    if (isPleasureOnly) penalty += 34;
  }

  return penalty;
}

function scoreKeywordOverlap(keywords, candidateText) {
  if (!keywords.length) return 0;

  const normalized = normalizeText(candidateText);
  let score = 0;

  keywords.forEach((keyword, index) => {
    if (normalized.includes(normalizeText(keyword))) {
      score += Math.max(4, 15 - index * 2.5);
    }
  });

  return score;
}

function scoreGenreHints(preferredGenres, candidateGenres) {
  if (!preferredGenres.length || !Array.isArray(candidateGenres) || candidateGenres.length === 0) {
    return 0;
  }

  const preferredSet = new Set(preferredGenres);
  const overlap = candidateGenres.filter(genre => preferredSet.has(genre)).length;
  return overlap * 5;
}

function scoreSourceBoost(candidate) {
  const sources = Array.isArray(candidate._sources) ? candidate._sources : [];
  let score = 0;

  if (sources.includes('curated')) score += 28;
  if (sources.includes('movie-themed') || sources.includes('tv-themed')) score += 11;
  if (sources.some(source => source.startsWith('movie-theme-') || source.startsWith('tv-theme-'))) score += 9;
  if (sources.includes('movie-rated') || sources.includes('tv-rated')) score += 6;
  if (sources.includes('movie-popular') || sources.includes('tv-popular')) score += 2;

  return score;
}

export function mergeCandidateBuckets(buckets) {
  const merged = new Map();

  buckets.forEach(({ source, items }) => {
    (items || []).forEach(item => {
      if (!item || item.id == null) return;

      const mediaType = item.media_type || (item.title ? 'movie' : 'tv');
      if (mediaType !== 'movie' && mediaType !== 'tv') return;

      const key = `${mediaType}:${item.id}`;
      const existing = merged.get(key);

      if (!existing) {
        merged.set(key, {
          ...item,
          media_type: mediaType,
          _sources: [source],
        });
        return;
      }

      merged.set(key, {
        ...existing,
        ...item,
        media_type: mediaType,
        overview: existing.overview || item.overview || '',
        poster_path: existing.poster_path || item.poster_path || null,
        vote_average: Math.max(Number(existing.vote_average) || 0, Number(item.vote_average) || 0),
        popularity: Math.max(Number(existing.popularity) || 0, Number(item.popularity) || 0),
        genre_ids: Array.isArray(existing.genre_ids) && existing.genre_ids.length > 0
          ? existing.genre_ids
          : (item.genre_ids || []),
        _sources: [...new Set([...(existing._sources || []), source])],
      });
    });
  });

  return [...merged.values()];
}

export function mapDetailsToCandidate(details, mediaType) {
  return {
    id: details.id,
    title: details.title ?? details.name,
    name: details.name ?? details.title,
    overview: details.overview || '',
    media_type: mediaType,
    poster_path: details.poster_path || null,
    release_date: details.release_date || null,
    first_air_date: details.first_air_date || null,
    vote_average: details.vote_average || 0,
    popularity: details.popularity || 0,
    genre_ids: Array.isArray(details.genres)
      ? details.genres.map(genre => genre?.id).filter(Boolean)
      : [],
    original_language: details.original_language || '',
    origin_country: Array.isArray(details.origin_country) ? details.origin_country : [],
  };
}

export function buildCuratedMatchIndex() {
  const matchIndex = new Map();

  Object.entries(curatedQuoteMatches).forEach(([tmdbId, quoteId]) => {
    const key = String(quoteId);
    const current = matchIndex.get(key) || [];
    current.push(String(tmdbId));
    matchIndex.set(key, current);
  });

  return matchIndex;
}

export function rankCandidates(profile, candidates, limit = HOME_RESULT_LIMIT) {
  const ranked = candidates
    .map(candidate => {
      const context = `${candidate.title || candidate.name || ''} ${candidate.overview || ''}`.trim();
      const candidateWeights = createWeightMap(analyzeWorkForThemes(context));
      const themeScore = scoreThemeOverlap(profile.themeWeights, context);
      const signalScore = scoreThemeSignals(profile.themeWeights, context);
      const keywordScore = scoreKeywordOverlap(profile.keywords, context);
      const genreScore = scoreGenreHints(profile.preferredGenres, candidate.genre_ids);
      const sourceBoost = scoreSourceBoost(candidate);
      const ratingScore = Math.max(0, Number(candidate.vote_average || 0) - 6) * 1.8;
      const popularityScore = Math.min(6, (Number(candidate.popularity) || 0) / 35);
      const missingOverviewPenalty = candidate.overview ? 0 : 12;
      const primaryThemeFit = scorePrimaryThemeFit(profile, candidateWeights, context);
      const evidenceScore = themeScore + signalScore + keywordScore;
      const weakThemePenalty = themeScore + signalScore < 16 && keywordScore < 8 ? 22 : 0;
      const noThemePenalty = themeScore === 0 && signalScore === 0 && keywordScore === 0 ? 28 : 0;
      const driftPenalty = scoreConceptDriftPenalty(profile, candidateWeights, context);

      const curatedTagScore = scorePhilosophicalTagsAgainstThemeWeights(
        getCuratedPhilosophicalProfile(candidate.id),
        profile.themeWeights,
      );

      return {
        ...candidate,
        _score:
          themeScore * 1.45
          + signalScore
          + keywordScore
          + genreScore
          + sourceBoost
          + ratingScore
          + popularityScore * 0.45
          + primaryThemeFit.bonus
          + curatedTagScore
          - missingOverviewPenalty
          - weakThemePenalty
          - noThemePenalty
          - primaryThemeFit.penalty
          - driftPenalty,
        _primaryThemeMisses: primaryThemeFit.misses.length,
        _evidenceScore: evidenceScore,
        _driftPenalty: driftPenalty,
      };
    })
    .sort((a, b) => b._score - a._score);

  const strongMatches = ranked.filter(item => item._score >= 30 && item._primaryThemeMisses === 0);
  const goodMatches = ranked.filter(item =>
    item._score >= 18
    && item._primaryThemeMisses <= 1
    && item._evidenceScore >= 10
    && item._driftPenalty < 42
  );
  const looseMatches = ranked.filter(item =>
    item._score >= 8
    && item._primaryThemeMisses <= 1
    && item._evidenceScore >= 7
    && item._driftPenalty < 34
  );
  const alignedPool = [
    ...strongMatches,
    ...goodMatches.filter(item => !strongMatches.includes(item)),
    ...looseMatches.filter(item => !strongMatches.includes(item) && !goodMatches.includes(item)),
  ];
  const pool = alignedPool.length > 0 ? alignedPool : ranked.slice(0, 3);

  return pool.slice(0, limit);
}
