/**
 * Baixa subsets woff2 (latin + latin-ext) do Google Fonts CSS API
 * e gera public/css/styles/fonts.css com font-display: swap.
 */
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const FONTS_DIR = join(ROOT, 'public', 'fonts');
const CSS_PATH = join(ROOT, 'public', 'css', 'styles', 'fonts.css');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400&family=DM+Sans:wght@300;400;500;600&display=swap';
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

function slugFromUrl(url, index) {
  const parsed = new URL(url);
  const last = parsed.pathname.split('/').pop() || `font-${index}.woff2`;
  return last.endsWith('.woff2') ? last : `font-${index}.woff2`;
}

function splitFontFaces(css) {
  const faces = [];
  const re = /\/\* ([^*]+) \*\/\s*@font-face \{[\s\S]*?\n\}/g;
  let match;
  while ((match = re.exec(css))) {
    faces.push({ subset: match[1].trim(), block: match[0] });
  }
  return faces;
}

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then(res => {
  if (!res.ok) throw new Error(`Google Fonts CSS ${res.status}`);
  return res.text();
});

await rm(FONTS_DIR, { recursive: true, force: true });
await mkdir(FONTS_DIR, { recursive: true });

const keptFaces = splitFontFaces(css).filter(face => KEEP_SUBSETS.has(face.subset));
if (!keptFaces.length) {
  throw new Error('No latin/latin-ext @font-face blocks found.');
}

const usedNames = new Set();
const replacements = [];
const urlRe = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g;

for (const face of keptFaces) {
  const urls = [...face.block.matchAll(urlRe)].map(match => match[1]);
  for (const url of urls) {
    if (replacements.some(entry => entry.url === url)) continue;
    let name = slugFromUrl(url, replacements.length);
    if (usedNames.has(name)) name = `${replacements.length}-${name}`;
    usedNames.add(name);

    const bin = Buffer.from(await fetch(url, { headers: { 'User-Agent': UA } }).then(res => {
      if (!res.ok) throw new Error(`Font download ${res.status} ${url}`);
      return res.arrayBuffer();
    }));
    await writeFile(join(FONTS_DIR, name), bin);
    replacements.push({ url, local: `/fonts/${name}`, bytes: bin.length });
  }
}

let localCss = keptFaces.map(face => face.block).join('\n\n');
for (const { url, local } of replacements) {
  localCss = localCss.split(url).join(local);
}

const banner = `/* Self-hosted Cormorant Garamond + DM Sans (latin + latin-ext, font-display: swap). Generated by scripts/download-fonts.mjs. */\n`;
await writeFile(CSS_PATH, `${banner}${localCss}\n`, 'utf8');

const files = await readdir(FONTS_DIR);
const totalKb = replacements.reduce((sum, item) => sum + item.bytes, 0) / 1024;
console.log(`Wrote ${files.length} woff2 files (${totalKb.toFixed(1)} KB) and fonts.css`);
